version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/App" # location of package.json
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
