version: "3.8"

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:5341"
      - "5341:5341/udp"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "YourStrongPassword"
    volumes:
      - seq_data:/data
    restart: unless-stopped

volumes:
  seq_data:
