-- AlterTable
ALTER TABLE `Bubbler` ALTER COLUMN `updatedAt` DROP DEFAULT;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `level` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `xp` INTEGER NOT NULL DEFAULT 0;
