version: "3.9"

services:
  app:
    image: ghcr.io/linuskang/bubbly:latest
    container_name: bubbly
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./App/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bubbly-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: waternearme
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
