name: Build & Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/arm64 \ # for Raspberry Pi 5
            -t ghcr.io/${{ github.repository }}/bubbly:${{ env.VERSION }} \
            -t ghcr.io/${{ github.repository }}/bubbly:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/bubbly:${{ env.VERSION }}
          docker push ghcr.io/${{ github.repository }}/bubbly:latest
